# school settings, can be overwritten in site/config/config.yml
# if you want these documents and links "externally managed", ie not visible as a default behaviour in the links and documents module
# create the respective categories and enter the ids here

schulcms:
  # school id for data synchronisation
  main_school_id: null

  # display recent event with report or image gallery
  event_is_recent_day_count: 60
  # display recently added report or images to event
  event_is_recent_report_day_count: 120

  # display stundent names setting
  display_student_names: false

  blackboard_news_type_id: null

  # registry for persistent page identifiers
  page_identifiers:
    team:     'team'
    events: 'events'

  # function_groups of functions displayed in team_member list [function_group_ids in sort order]
  active_function_groups:
    team_members_with_classes: [1, 2, 8, 12, 15]
    team_members_others: [4, 5, 6, 9, 10, 16]

  # classes of types should not be displayed in class list
  exclude_class_types: []

  # optional subpage identifiers used in SchoolFilter for the virtual navigation items
  subpages_classes_identifiers: []

  # display image name allows to hide meaningless names from automatic upload
  gallery_display_image_name: true

documentation:
  support_info:
    heading: 'Support-Infos SchulCMS'
    link_text: 'Infos Supportablauf & E-Mail-Adresse'
    link: 'http://www.schulcms.ch/support'

frontend:
  inherit_contents: false
  protect_email_addresses: true

# example navigation like in pilot project
navigations:
  main:
    1:
      - {template: main_current, on: 'is_current'}
      - {template: main_active, on: 'is_active'}
      - {template: main_default}
  secondary:
    2:
      - {template: secondary_level_default, on: is_current}
      - {template: secondary_level_default, on: is_child_of_current|is_sibling_of_active|is_active}
      - {show: false}
  top_css:
    no_newline: true
    0:
      - {template_inline: '{{name}}', on: is_current}
    1:
      - {template_inline: '{{name}}', on: is_active}

# default language
session_default:
  language: de &fe_language
  content_language: *fe_language

# simple richtext toolbar defaults
text_module:
  toolbar:
    -
      - ['Bold', '-', 'BulletedList']
      - ['Link', 'Unlink']
      - ['Image']
      - ['Table']
      - ['Format']
      - ['Undo', 'Redo']
      - ['RemoveFormat', 'PasteText', 'Source']
      - ['Maximize']
  richtext_width: 700
  format_tags: 'p;h1;h2;h3'
