# school settings, can be overwritten in site/config/config.yml
# if you want these documents and links "externally managed", ie not visible as a default behaviour in the links and documents module
# create the respective categories and enter the ids here

school_settings:
	***REMOVED***_school_id: 40
	
	externally_managed_document_categories:
		event_documents: 14
		service_documents: 18
		team_member_portraits: 10
		school_class_portraits: 11
		school_class_schedules: 12
		school_class_weekplans: 13
		
	externally_managed_link_categories:
		school_class_links: 2
	internally_used_service_category: null
	
	display_student_names: false
	
	page_identifiers:
		classes: 	'classes'
		team: 		'team'
		services: 'services'
		events: 'events'
		
	#declare function_group_ids in sort order
	active_function_groups:
		teachers_require_classes: []
		teachers: [1, 2]
		others: [6, 7, 12]

# example navigation like in pilote project ***REMOVED***
navigations:
	main:
		1:
			- {template: main_current, on: 'is_current'}
			- {template: main_active, on: 'is_active'}
			- {template: main_default}
	secondary:
		2:
			- {template: secondary_level_default, on: is_current}
			- {template: secondary_level_default, on: is_child_of_current|is_sibling_of_active|is_active}
			- {show: false}
	top_css:
		no_newline: true
		0:
			- {template_inline: '{{name}}', on: is_current}
		1:
			- {template_inline: '{{name}}', on: is_active}

# default language
session_default:
  language: de &fe_language
  content_language: *fe_language

# simple richtext toolbar defaults
text_module:	
	toolbar: 
		- 
			- ["Bold", "Italic"]
			- ["Link", "Unlink", "-", "Image"]
			- ["NumberedList", "BulletedList"]
			- ["Undo", "Redo"]
			- ["Format"]
			- ["RemoveFormat", "Source", "-", "Maximize"] 
	richtext_width: 700




