libraries:
  wok:
    url: 'wok/build/Wok.min.js'
    url_uncompressed: 'wok/src/Wok.js'
  react:
    url: '//cdnjs.cloudflare.com/ajax/libs/react/${version}/react.min.js'
    url_uncompressed: '//cdnjs.cloudflare.com/ajax/libs/react/${version}/react.js'
