libraries:
  wok:
    url: 'wok/build/Wok.min.js'
    url_uncompressed: 'wok/src/Wok.js'
  react:
    url: 'http://fb.me/react-${version}.min.js'
    url_uncompressed: 'http://fb.me/react-${version}.js'
