admin_menu:
  left:
    - preview
    - edit
    -
      - ~
      - module.events
      - module.classes
      - module.team_members
      - module.services
      - module.news
      - ~
      - module.strings
      - module.documents
      - module.links
      - ~
      - module.users
    - module.dashboard
    - ~
    - tag
    - documentation
  right:
    - activity
    - domain_name
    - logo
    - user
    - logout

dashboard:
  layout: 2cols2thirds
  widgets:
    -
      config: [ ]
      color: 'rgb(20, 142, 164)'
      collapsed: false
      type: my_classes
      title: 'Meine Klassen'
      container: 'column-1'
    -
      config:
      color: 'rgb(242, 188, 0)'
      collapsed: false
      type: documentation
      title: 'Benutzer-Dokumentation'
      container: 'column-2'
